services:
  database:
    container_name: database
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: embrapa
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: embrapa
    networks:
      - default
    depends_on:
      - database

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - database

networks:
  default:
    name: local-network
    external: false
